version: "3"

services:
  web:
    container_name: reverse_proxy
    image: traefik:v2.0.5

    ports:
      # The Web UI
      #- "8080:8080"
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./manifest/etc/traefik:/etc/traefik

    labels:
      - "traefik.http.middlewares.traefik-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-http.entrypoints=web"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https@docker"
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik.tls=true"

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    container_name: whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
